export enum TKeys {
  Explore = "explore",
  Range = "range",
  Date = "date",
  Bookmarks = "bookmarks",
  Count = "count",
  Saved = "saved",
  Save = "save",
  Home = "home",
  RemoveBookmarks = "remove-bookmarks",
  StartExploring = "start-exploring",
  InfoSelectDate = "info-select-date",
  InfoDateNotValid = "info-date-not-valid",
  InfoNoResultsFound = "info-no-results-found",
  InfoLost = "info-lost",
  InfoSelectRange = "info-select-range",
  InfoDateIntervalLength = "info-date-interval-length",
}
